---
- name: create users with sudo rules
  user:
    name: "{{ item.userName }}"
    password: "{{ item.password | password_hash('sha512', 'salt') }}"
    shell: /bin/bash
  loop: "{{ password | dict2items(key_name='userName', value_name='password') }}"

- name: move to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: '{{ item }} ALL=(ALL)ALL'
    validate: 'visudo -cf %s'
  loop: "{{ user_add }}"


- name: move someuser to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: '{{ item }} ALL=(ALL)NOPASSWD:ALL'
    validate: 'visudo -cf %s'
  loop:
    - someuser

- name: add authorized_keys file with authorized_keys
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', './ssh_key/authorized_keys.{{ item }}') }}"
  loop: "{{ user_add }}"