---
- name: get apt-key grafana
  become: yes
  apt_key: 
    url: https://packages.grafana.com/gpg.key
    state: present
    validate_certs: false

- name: Add Grafana repository [Debian/Ubuntu]
  become: yes
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    update_cache: yes

- name: update_cache
  become: yes
  apt:
    update_cache: yes

- name: install_grafana
  become: yes
  apt:
    package:
      - grafana 
    state: present
    update_cache: yes
  notify: "Start Grafana server"
  tags:
    - install_grafana